name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  semgrep:
    name: semgrep
    runs-on: ubuntu-latest
    container:
      returntocorp/semgrep
    steps:
      - uses: actions/checkout@v4
      - run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: 7134549292172e42127d0f6e00598435c7da8ad224221889b5612bd4276a5f52
